language: node_js
node_js:
  - "4"
  - "5"
env:
  global: 
    - NODE_ENV=test
    - "OTR_CONFIG='{ \"http\" : {\"port\" : 1337 } }'"
services:
  - mongodb
install: 
  - npm install -g istanbul
  - npm install -g mocha
  - npm install 
before_script:
  - npm run gen-key-signed-cert
  - mocha --version
after_script:
  - istanbul cover --hook-run-in-context ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec test && NODE_COVERALLS_DEBUG=1 cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
